In [2]:
import pandas as pd
df=pd.read_excel('allpubgwpnstats.xlsx')
df

            Weapon  Damage    Ammo  Time to kill(in sec)     WeaponType
0           Sickle      60     NaN                 1.500          Melle
1          Crowbar      60     NaN                 1.500          Melle
2          Machete      60     NaN                 1.500          Melle
3              Pan      80     NaN                 1.500          Melle
4             S686     216     12G                   NaN       shortgun
5            S1897     216     12G                   NaN       shortgun
6             S12K     198     12G                   NaN       shortgun
7        Sawed-off     160     12G                 0.250         pistol
8              P92      35     9mm                 0.540         pistol
9            P1911      41    0.45                 0.750         pistol
10           R1895      55    7.62                 1.200         pistol
11            P18C      23     9mm                 0.420         pistol
12             R45      55    0.45                 0.750         pistol
13            M249      45    5.56                 0.230     MachineGun
14           DP-28      51    7.62                 0.330     MachineGun
15             UZI      26     9mm                 0.290  submachinegun
16            UMP9      39     9mm                 0.370  submachinegun
17          Vector      34    0.45                 0.220  submachinegun
18       Tommy Gun      40    0.45                 0.340  submachinegun
19             SKS      53    7.62                 0.200      DMR rifle
20             VSS      41     9mm                 0.260      DMR rifle
21          Mini14      46    5.56                 0.300      DMR rifle
22            Mk14      61    7.62                 0.180      DMR rifle
23             SLR      58    7.62                 0.200      DMR rifle
24             QBU      48    5.56                 0.945      DMR rifle
25             AKM      49    7.62                 0.300   AssaultRifle
26           M16A4      43    5.56                 0.220   AssaultRifle
27          SCAR-L      43    5.56                 0.290   AssaultRifle
28            M416      43    5.56                 0.260   AssaultRifle
29           GROZA      49    7.62                 0.240   AssaultRifle
30             AUG      43    5.56                 0.260   AssaultRifle
31          Kar98K      75    7.62                 3.800     BoltAction
32             M24      79    7.62                 1.800     BoltAction
33             AWM     120     300                 1.850     BoltAction
34           Win94      66    0.45                 1.200     BoltAction
35        Crossbow     105  Arrows                 3.800         Others
36  Jump and Punch      38     NaN                 4.000      HandPunch
37            Fist      18     NaN                 2.970      HandPunch

In [131]:
#lets group the weapons 
df.dropna()
wpn_type=df.groupby('WeaponType')
for types,weapons in wpn_type:
    print('Weapon category :',types)
    print()
    print('Statistics :\n',weapons)
    print('\n\n')

Weapon category : AssaultRifle

Statistics :
     Weapon  Damage  Ammo  Time to kill(in sec)    WeaponType
29     AKM    49.0  7.62                  0.30  AssaultRifle
30   M16A4    43.0  5.56                  0.22  AssaultRifle
31  SCAR-L    43.0  5.56                  0.29  AssaultRifle
32    M416    43.0  5.56                  0.26  AssaultRifle
33   GROZA    49.0  7.62                  0.24  AssaultRifle
34     AUG    43.0  5.56                  0.26  AssaultRifle



Weapon category : BoltAction

Statistics :
     Weapon  Damage  Ammo  Time to kill(in sec)  WeaponType
36  Kar98K    75.0  7.62                  3.80  BoltAction
37     M24    79.0  7.62                  1.80  BoltAction
38     AWM   120.0   300                  1.85  BoltAction
39   Win94    66.0  0.45                  1.20  BoltAction



Weapon category : DMR rifle

Statistics :
     Weapon  Damage  Ammo  Time to kill(in sec) WeaponType
22     SKS    53.0  7.62                 0.200  DMR rifle
23     VSS    41.0   9mm                 0.260  DMR rifle
24  Mini14    46.0  5.56                 0.300  DMR rifle
25    Mk14    61.0  7.62                 0.180  DMR rifle
26     SLR    58.0  7.62                 0.200  DMR rifle
27     QBU    48.0  5.56                 0.945  DMR rifle



Weapon category : HandPunch

Statistics :
             Weapon  Damage Ammo  Time to kill(in sec) WeaponType
43  Jump and Punch    38.0  NaN                  4.00  HandPunch
44            Fist    18.0  NaN                  2.97  HandPunch



Weapon category : MachineGun

Statistics :
    Weapon  Damage  Ammo  Time to kill(in sec)  WeaponType
14   M249    45.0  5.56                  0.23  MachineGun
15  DP-28    51.0  7.62                  0.33  MachineGun



Weapon category : Melle

Statistics :
     Weapon  Damage Ammo  Time to kill(in sec) WeaponType
0   Sickle    60.0  NaN                   1.5      Melle
1  Crowbar    60.0  NaN                   1.5      Melle
2  Machete    60.0  NaN                   1.5      Melle
3      Pan    80.0  NaN                   1.5      Melle



Weapon category : Others

Statistics :
       Weapon  Damage    Ammo  Time to kill(in sec) WeaponType
41  Crossbow   105.0  Arrows                   3.8     Others



Weapon category : pistol

Statistics :
        Weapon  Damage  Ammo  Time to kill(in sec) WeaponType
8   Sawed-off   160.0   12G                  0.25     pistol
9         P92    35.0   9mm                  0.54     pistol
10      P1911    41.0  0.45                  0.75     pistol
11      R1895    55.0  7.62                  1.20     pistol
12       P18C    23.0   9mm                  0.42     pistol
13        R45    55.0  0.45                  0.75     pistol



Weapon category : shortgun

Statistics :
   Weapon  Damage Ammo  Time to kill(in sec) WeaponType
5   S686   216.0  12G                   NaN   shortgun
6  S1897   216.0  12G                   NaN   shortgun
7   S12K   198.0  12G                   NaN   shortgun



Weapon category : submachinegun

Statistics :
        Weapon  Damage  Ammo  Time to kill(in sec)     WeaponType
17        UZI    26.0   9mm                  0.29  submachinegun
18       UMP9    39.0   9mm                  0.37  submachinegun
19     Vector    34.0  0.45                  0.22  submachinegun
20  Tommy Gun    40.0  0.45                  0.34  submachinegun

In [132]:
#let us the type of ammo that weapons use
ammo=df.groupby('Ammo')
for ammotype,guns in ammo:
    print('Ammo Type : ',ammotype)
    print()
    print('Statistics :\n',guns)
    print('\n\n')

Ammo Type :  0.45

Statistics :
        Weapon  Damage  Ammo  Time to kill(in sec)     WeaponType
10      P1911    41.0  0.45                  0.75         pistol
13        R45    55.0  0.45                  0.75         pistol
19     Vector    34.0  0.45                  0.22  submachinegun
20  Tommy Gun    40.0  0.45                  0.34  submachinegun
39      Win94    66.0  0.45                  1.20     BoltAction



Ammo Type :  5.56

Statistics :
     Weapon  Damage  Ammo  Time to kill(in sec)    WeaponType
14    M249    45.0  5.56                 0.230    MachineGun
24  Mini14    46.0  5.56                 0.300     DMR rifle
27     QBU    48.0  5.56                 0.945     DMR rifle
30   M16A4    43.0  5.56                 0.220  AssaultRifle
31  SCAR-L    43.0  5.56                 0.290  AssaultRifle
32    M416    43.0  5.56                 0.260  AssaultRifle
34     AUG    43.0  5.56                 0.260  AssaultRifle



Ammo Type :  7.62

Statistics :
     Weapon  Damage  Ammo  Time to kill(in sec)    WeaponType
11   R1895    55.0  7.62                  1.20        pistol
15   DP-28    51.0  7.62                  0.33    MachineGun
22     SKS    53.0  7.62                  0.20     DMR rifle
25    Mk14    61.0  7.62                  0.18     DMR rifle
26     SLR    58.0  7.62                  0.20     DMR rifle
29     AKM    49.0  7.62                  0.30  AssaultRifle
33   GROZA    49.0  7.62                  0.24  AssaultRifle
36  Kar98K    75.0  7.62                  3.80    BoltAction
37     M24    79.0  7.62                  1.80    BoltAction



Ammo Type :  300

Statistics :
    Weapon  Damage Ammo  Time to kill(in sec)  WeaponType
38    AWM   120.0  300                  1.85  BoltAction



Ammo Type :  12G

Statistics :
       Weapon  Damage Ammo  Time to kill(in sec) WeaponType
5       S686   216.0  12G                   NaN   shortgun
6      S1897   216.0  12G                   NaN   shortgun
7       S12K   198.0  12G                   NaN   shortgun
8  Sawed-off   160.0  12G                  0.25     pistol



Ammo Type :  9mm

Statistics :
    Weapon  Damage Ammo  Time to kill(in sec)     WeaponType
9     P92    35.0  9mm                  0.54         pistol
12   P18C    23.0  9mm                  0.42         pistol
17    UZI    26.0  9mm                  0.29  submachinegun
18   UMP9    39.0  9mm                  0.37  submachinegun
23    VSS    41.0  9mm                  0.26      DMR rifle



Ammo Type :  Arrows

Statistics :
       Weapon  Damage    Ammo  Time to kill(in sec) WeaponType
41  Crossbow   105.0  Arrows                   3.8     Others

In [144]:
#lets us know the weapon with highest damage


dmax=   df[['Weapon','Damage']][df.Damage==df.Damage.max()]
dmax

  Weapon  Damage
5   S686   216.0
6  S1897   216.0

In [141]:
#lets ud know the weapon with highest speed
import numpy as np
df.fillna({
    'Time to kill(in sec)':np.NaN
})
print('Weapon with highest damage:')

df[['Weapon','Time to kill(in sec)']][df['Time to kill(in sec)']==df['Time to kill(in sec)'].min()]

Weapon with highest damage:

   Weapon  Time to kill(in sec)
25   Mk14                  0.18